### ISSUE TITLE
Adding Paycent as default token in MEW

### ISSUE THREAD

**Issue by vtaneja92** [MyEtherWallet/ethereum-lists#1080]
Hi,

How to add Paycent as default token in MEW? Can't do it following the steps from here - https://kb.myetherwallet.com/posts/tokens/adding-token-as-a-default/

Paycent - https://etherscan.io/token/0x0142c3b2fc51819b5af5dfc4aa52df9722790851

Thanks

**Comment by gesseekur** [comment]
Please fill out this information: 
{
"symbol": "",

"name": "",

"type": "ERC20",

"address": "",
"ens_address": "",
"decimals": ,
"website": "",
"logo": {
    "src": "",
    "width": "",
    "height": "",
    "ipfs_hash": ""
},
"support": {
    "email": "",
    "url": ""
},
"social": {
    "blog": "",
    "chat": "",
    "facebook": "",
    "forum": "",
    "github": "",
    "gitter": "",
    "instagram": "",
    "linkedin": "",
    "reddit": "",
    "slack": "",
    "telegram": "",
    "twitter": "",
    "youtube": ""
}
}
