### ISSUE TITLE
Add PodbumCoin to Default

### ISSUE THREAD

**Issue by podbum** [MyEtherWallet/ethereum-lists#1086]
`{
  "symbol": "PBUM",
  "name": "PodBum",
  "type": "ERC20",
  "address": "0x85aaC0E07a64ceF49d6133DBF4AC253dDF0C8Ce9
  "ens_address": "",
  "decimals": 18,
  "website": "https://www.podbumcoin.com",
  "logo": { "src": "", "width": "", "height": "", "ipfs_hash": "" },
  "support": { "email": "hello@podbumcoin.com", "url": "" },
  "social": {
    "blog": "https://hangoutspace.wordpress.com",
    "chat": "",
    "facebook": "",
    "forum": "",
    "github": "https://github.com/podbum/coin,
    "gitter": "",
    "instagram": "http://www.instagram/podbum",
    "linkedin": "",
    "reddit": "https://www.reddit.com/user/podbum/",
    "slack": "",
    "telegram": "https://t.me/joinchat/podbum",
    "twitter": "https://twitter.com/podbum",
    "youtube": ""
  }
}`

**Comment by gesseekur** [comment]
can't find this on etherscan. closing.
