### ISSUE TITLE
New token type for PDATA?

### ISSUE THREAD

**Issue by brianmcgee** [MyEtherWallet/ethereum-lists#1136]
The `type` field for the `PDATA` symbol has the value `Opiria & PDATA Token`. Should this be one of `GENERIC`, `ERC20`, `ERC721` or do you intend to introduce a new token type? If it is intended as a new token type, can you make it more amenable to processing e.g. OPIRIA_PDATA

```json
{"symbol":"PDATA","type":"Opiria & PDATA Token","address":"0x0db03B6CDe0B2d427C64a04FeAfd825938368f1F","decimals":18,"name":"PDATA","ens_address":"","website":"https://opiria.io","logo":{"src":"https://www.opiria.io/static/images/logo-solo.png","width":95,"height":110,"ipfs_hash":""},"support":{"email":"sales@opiria.com","url":"www.opiria.io"},"social":{"blog":"","chat":"","facebook":"","forum":"","github":"https://github.com/opiria-pdata/Pdata","gitter":"","instagram":"","linkedin":"","reddit":"","slack":"","telegram":"https://t.me/PDATAtoken","twitter":"","youtube":""}}
```
Currently this is breaking EthVM processing https://github.com/EthVM/EthVM/issues/574

**Comment by gamalielhere** [comment]
@brianmcgee that's supposed to be ERC20. I'll fix that right now
