### ISSUE TITLE
KeepKey error

### ISSUE THREAD

**Issue by Jacson2000** [MyEtherWallet/ethereum-lists#1137]
{"exception":{"values":[{"type":"TypeError","value":"Cannot read property 'getAddressString' of null","stacktrace":{"frames":[{"colno":12354,"filename":"https://www.myetherwallet.com/js/vendors.2aff9bcd.js","function":"HTMLButtonElement.r","in_app":true,"lineno":513},{"colno":51712,"filename":"https://www.myetherwallet.com/js/vendors.2aff9bcd.js","function":"HTMLButtonElement.Ja.i._wrapper","in_app":true,"lineno":42},{"colno":13533,"filename":"https://www.myetherwallet.com/js/vendors.2aff9bcd.js","function":"HTMLButtonElement.n","in_app":true,"lineno":42},{"colno":11644,"filename":"https://www.myetherwallet.com/js/vendors.2aff9bcd.js","function":"nt","in_app":true,"lineno":42},

@keepkeyjon

**Comment by keepkeyjon** [comment]
@gamalielhere mind moving this ticket over to https://github.com/MyEtherWallet/MyEtherWallet? I'll triage.

**Comment by keepkeyjon** [comment]
Looks a lot like https://github.com/MyEtherWallet/MyEtherWallet/issues/1083#issuecomment-494557748

**Comment by gamalielhere** [comment]
Will do @keepkeyjon. I'll make a separate issue for it since the one you linked to has several
