### ISSUE TITLE
darklist?

### ISSUE THREAD

**Issue by moonseoklee** [MyEtherWallet/ethereum-lists#1150]
Can you trust these darklists? What are the criteria for dark list classification or collection sites?

**Comment by gamalielhere** [comment]
@moonseoklee these dark lists are submitted by the community. We also do research about the dark listed address/urls before approving so take that as you will.

**Comment by moonseoklee** [comment]
@gamalielhere Where is the community? And will the update be made for darklist? Thanks for your reply

**Comment by gamalielhere** [comment]
@moonseoklee the community means the people who chose to contribute.. darklists will be updated as people report more site/addresses. Furthermore, we also reference other organization's darklist, namely [Iosiro](https://github.com/iosiro/counter_phishing_blacklist) and [EAL](https://github.com/409H/EtherAddressLookup/tree/master/blacklists).
