### ISSUE TITLE
Add MVC token to default

### ISSUE THREAD

**Issue by maivangcity** [MyEtherWallet/ethereum-lists#1205]
{
"symbol": "MVC",
"name": "MaiVangCity",
"type": "ERC20",
"address": "0xebfc4fa869a6db3cbd6a849b5b656bae4aba68f0",
"ens_address": "",
"decimals": 0,
"website": "https://maivangcity.com",
"logo": {
"src": "",
"width": "",
"height": "",
"ipfs_hash": ""
},
"support": { "email": "contact@maivangcity.com", "url": "https://maivangcity.com" },
"social": {
"blog": "https://maivangcity.com/blog",
"chat": "",
"facebook": "https://www.facebook.com/thanhphomaivang",
"forum": "",
"github": "",
"gitter": "",
"instagram": "",
"linkedin": "",
"reddit": "https://www.reddit.com/r/maivangcity",
"slack": "",
"telegram": "",
"twitter": "https://twitter.com/maivangcity",
"youtube": ""
}
}

**Comment by gamalielhere** [comment]
[Please follow instructions listed here](https://github.com/MyEtherWallet/ethereum-lists/blob/master/README.md#tokens)
