### ISSUE TITLE
Add VREO token to Default

### ISSUE THREAD

**Issue by AndreasSchemm** [MyEtherWallet/ethereum-lists#1257]
{
"symbol": "VREO",
"name": "VREO Token",
"type": "ERC20",
"address": "0xe4eb6085899a836abd083fad566ac74f05974947",
"ens_address": "",
"decimals": 18,
"website": "https://ico.vreo.io",
"logo": {
"src": "",
"width": "",
"height": "",
"ipfs_hash": ""
},
"support": { "email": "ico@vreo.io", "url": "https://ico.vreo.io" },
"social": {
"blog": "https://medium.com/@vreo,
"chat": "",
"facebook": "https://www.facebook.com/pgvreo/",
"forum": "",
"github": "https://github.com/Vreo",
"gitter": "",
"instagram": "",
"linkedin": "",
"reddit": "",
"slack": "",
"telegram": "",
"twitter": "https://twitter.com/pg_vreo",
"youtube": ""
}
}

**Comment by gesseekur** [comment]
hi , are the websites and emails updated ? I see https://vreo.io/  on etherscan. Thanks!
