### ISSUE TITLE
Adding Token as Default Token.  Cant find the pencil icon.

### ISSUE THREAD

**Issue by gravitastech** [MyEtherWallet/ethereum-lists#1284]
Hi Support,
https://kb.myetherwallet.com/en/tokens/adding-token-as-a-default/
I follow the instruction to login to github, and click the link above.

Login or join GitHub.
Click the pencil icon in upper right.
Scroll to the letter of your token (they are in alphabetical order).

I dont see the Pencil icon in upper right.  I only see Watch , Star, Fork.  
The top right of the screen is Notification , + (new repositiory) and my profile.

Please see the attached screen.  Where can i find the pencil icon to select my token alphabet?

Thank you.

I would like to add 2 tokens into mew wallet as default token.
![mewgithub](https://user-images.githubusercontent.com/54106881/66183841-cbd4e000-e6ac-11e9-9285-5416580c0b80.jpg)

**Comment by purplematter** [comment]
Pencil is for corrections or deletions of existing files. For additions, you have to click "Create new file" and name your file with the ethereum address with a .json extension.
 e.g: _0xBbe761EA1447A20b75aA485b7BCad4837415d7D7.json_

(this information can be found in the [README.md](https://github.com/MyEtherWallet/ethereum-lists/blob/master/README.md))
