### ISSUE TITLE
ADD BBA to Default

### ISSUE THREAD

**Issue by bbacoder007** [MyEtherWallet/ethereum-lists#1342]
{
"symbol": "BBA",
"name": "BBA Token",
"type": "ERC20",
"address": "0x73621534d00d80f675b7e868860f97edb3c03935",
"ens_address": "",
"decimals": 18,
"website": "https://bba.plus",
"logo": {
"src": "",
"width": "",
"height": "",
"ipfs_hash": ""
},
"support": { "email": "bbacoder@gmail.com", "url": "https://bba.plus" },
"social": {
"blog": "",
"chat": "",
"facebook": "",
"forum": "",
"github": "",
"gitter": "",
"instagram": "",
"linkedin": "",
"reddit": "",
"slack": "",
"telegram": "",
"twitter": "",
"youtube": ""
}
}

**Comment by cristine2114** [comment]
#1392
