### ISSUE TITLE
urls-darklist.json 404 Not Found

### ISSUE THREAD

**Issue by scoope3** [MyEtherWallet/ethereum-lists#139]
Hi,

It appears that urls-darklist.json is currently down. Do you have an ETA for when this will be back up? 

Thank you.

**Comment by 409H** [comment]
Hi, could you be referring to ESD blacklist? https://etherscamdb.info/data/blacklist.json

ethereum-lists darklist of urls is served by raw.github - https://raw.githubusercontent.com/MyEtherWallet/ethereum-lists/master/urls/urls-darklist.json

**Comment by scoope3** [comment]
Hi, the issue was resolved. I was referring to the old location: https://raw.githubusercontent.com/MyEtherWallet/ethereum-lists/master/urls-darklist.json. 

Thanks for the quick response. It simply moved :).
