### ISSUE TITLE
my eth was stole 

### ISSUE THREAD

**Issue by blockChainB** [MyEtherWallet/ethereum-lists#148]
my eth was stole ,wo can help me  ? the hack's address 
       0x434E9F6A1ac134FDa3E7cEb3fd67c3D9B3518737

**Comment by 409H** [comment]
Can you give more information on how it was stolen?

Once a transaction is signed, broadcasted, and confirmed, you can't get a refund. It's by design of the blockchain. Probably won't get your funds back - sorry.

**Comment by andreis123** [comment]
my ADX tokens were stolen and sent to this address also. Is there anything i can do>

**Comment by Xikun** [comment]
my 75 eth were also stolen and then sent to https://etherscan.io/address/0xb978d9924efb5287a465a3148faf01435dee1299
Unfortunately, I think we cannot do anything about it.

**Comment by friedger** [comment]
Address has already been added to the dark list. Can be closed.

**Comment by Tom-Smat** [comment]
hello everyone i just had a bad day at least 97 ether stolen from me as i copied an address to send it to and now it sent it to another address what do i do before its too late

**Comment by Tom-Smat** [comment]
i dont know anything about ethereum

**Comment by LeCobain** [comment]
All my ETH was stoled.. Can I recovered it?
https://etherscan.io/address/0x1af6413d7f974d0336712be0749d3d7e526b5023
This address robbed me :(

**Comment by Kdricardo** [comment]
my 16.08 eth were also stolen and then sent to https://etherscan.io/address/0x3fd69b6d48e520e01d189e8d0bb37c5807e07f67
Unfortunately, I think we cannot do anything about it.
