### ISSUE TITLE
Fully remove old token

### ISSUE THREAD

**Issue by Katafalkas** [MyEtherWallet/ethereum-lists#1646]
Hello. I have lately replace old token with a new one:
https://github.com/MyEtherWallet/ethereum-lists/pull/1614
https://github.com/MyEtherWallet/ethereum-lists/pull/1615

But when I browse MEW token list - I can still see the old token. Any suggestions where else should I removing/adding it?
As well as that - old token seems to have Logo, and new one does not.

<img width="508" alt="Screenshot 2020-10-26 at 08 43 47" src="https://user-images.githubusercontent.com/1636440/97141582-a8714d00-1767-11eb-8820-685f33c58a07.png">

**Comment by Katafalkas** [comment]
Anyone?

**Comment by gamalielhere** [comment]
Apologise for the delay but I removed the token, it should be removed on MEW on the next release
