### ISSUE TITLE
Issue adding a token 

### ISSUE THREAD

**Issue by gnarco** [MyEtherWallet/ethereum-lists#1689]
Hi @gamalielhere

I tag you because, it seems that you're in charge of merging token request.

We added our token, but during the flow is was deleted.
Here the PR : https://github.com/MyEtherWallet/ethereum-lists/pull/1677

Last commit on master : 
https://github.com/MyEtherWallet/ethereum-lists/commits/master

#1682 is your merge
Then a bot "recompile" : https://github.com/MyEtherWallet/ethereum-lists/commit/fff899200d1b414e3e4f976b1fa0a57953dd329e
(add our token to "dist", but remove it from src ?)

then when a new "Recompile" occur, everything is deleted 
https://github.com/MyEtherWallet/ethereum-lists/commit/f084130f4565caaca8ed61d542dff315e8cd60aa 

So I think there's an issue in the build process.

Happy to help !
Thanks

**Comment by gamalielhere** [comment]
Thanks for bringing this up, I disabled part of the compile that deletes the files and will figure that part out. I pushed your token back up.
