### ISSUE TITLE
Problem with Pool Request processing

### ISSUE THREAD

**Issue by Vasilii79** [MyEtherWallet/ethereum-lists#1690]
Dear MEW support, you have merged our Pool Request 24 days ago: https://github.com/MyEtherWallet/ethereum-lists/pull/1668
But, YOUC token logo is still not appeared on MEW-(

Maybe we should add any additional info to PR to speed up the process?

**Comment by EGreg** [comment]
We are experiencing the same problem. [Made initial commit back in June](https://github.com/MyEtherWallet/ethereum-lists/commit/32e7f814d85d896db8e2a4ad2d87a8a9af224c73#diff-e13fddcffb4b81a21265ec43492c16678126518d1c88f54127a3c1b84e8685b9) and it's not appearing in the MEW wallet.

Just now we have updated the support email and a few other things, like our YouTube channel URL.
Please @kaichen @roderik can you give us an update on how this is processed?

**Comment by Vasilii79** [comment]
> Made initial commit back in June

Hey man, just checked your token on etherscan. To get token added on MEW you nee:
1. update your etherscan by adding logo and Social Profile links first, 
2. then do as described here: https://tokpie.io/blog/how-to-add-token-to-mew-permanent-default-token-list/

**Comment by EGreg** [comment]
We did 2 already. How do we do 1, and is it required before being approved?

**Comment by Vasilii79** [comment]
> We did 2 already. How do we do 1, and is it required before being approved?

1 is the basic things you must do. Just click on Update here https://etherscan.io/token/0x6Ef5febbD2A56FAb23f18a69d3fB9F4E2A70440B
To pass Etherscan (to get logo and Social profile added) you need to have your official email on your website footer and team section with LinkedIn profiles.
