### ISSUE TITLE
0xeA7aA1eDd21735A5ab05EE3E90869016191e274E token symbol undefined

### ISSUE THREAD

**Issue by cryptotxalert** [MyEtherWallet/ethereum-lists#1791]
The json definition does not meet spec and Symbol is undefined

https://github.com/MyEtherWallet/ethereum-lists/blob/master/src/tokens/eth/0xeA7aA1eDd21735A5ab05EE3E90869016191e274E.json

**Comment by gamalielhere** [comment]
@cryptotxalert thanks for letting me know, will fix it!
