### ISSUE TITLE
Discussion: naming scheme

### ISSUE THREAD

**Issue by ligi** [MyEtherWallet/ethereum-lists#186]
currently the naming uses a 3 letter indicator for the network.Like this:

```
tokens-etc.json  tokens-kov.json  tokens-rop.json
tokens-eth.json  tokens-rin.json  tokens-rsk.json
```

I would suggest to use the chain-Id. So you need to have one less mapping and it is more future proof. 
like this:

tokens-rin.json -> tokens-4.json
tokens-eth.json -> tokens-1.json

**Comment by 409H** [comment]
Hi Ligi, I'm unaware of the chain ids - is this a de-facto numbering system (ie: `4` is _always_ rinkeby)?

**Comment by ligi** [comment]
To be honest I struggle to find the "official documentation" on chainId currently - but this is the case - each chain has a Id ..
You see it e.g. mentioned in https://github.com/ethereum/eips/issues/155
We can also do the mapping in the scripts - but the mapping should IMHO not be done on the consumers

**Comment by 409H** [comment]
> To be honest I struggle to find the "official documentation" on chainId currently - but this is the case - each chain has a Id

I understand - all good here :+1: 

> We can also do the mapping in the scripts

My understanding for this repo is for the `.json` files to be consumed by an application, and it's just a repo to hold data dumps. Which scripts are you referencing here to do the mapping?

**Comment by ligi** [comment]
This script which is currently checking validity:
https://github.com/MyEtherWallet/ethereum-lists/blob/master/src/main/kotlin/ethereum/Main.kt

and generates minimized versions of the json
could also do the mapping.

**Comment by 409H** [comment]
Ah, okay, totally missed that. 

I'm neutral to this change, but if we do it, we'd need to document the id mapping in `CONTRIBUTING.md` :)

**Comment by tayvano** [comment]
I think this is a good plan. However, for my own sanity, can we somehow put the chain name at the end (which isn't used for validation)?

Eg tokens_1-rop or something. 

The other thing is that there are chain IDs of 2 and maybe 3 numbers. So we should probably just do tokens_001 to be safe. 

I can also check on how this is operating on v4.

**Comment by ligi** [comment]
perhaps it is better in the validation/minimizing step - ideally it is just the number - so you can directly load - without using a wildcard or use the mapping - just "tokens-${chainid}.json"
I will prepare for this a PR. PS: there is another one open: https://github.com/MyEtherWallet/ethereum-lists/pulls

**Comment by ligi** [comment]
> can you link me to the official documentation?

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
