### ISSUE TITLE
Token merged but does not appear into mew interface

### ISSUE THREAD

**Issue by bitcoinasiasite** [MyEtherWallet/ethereum-lists#1891]
Hi @gamalielhere thank you for merging  [https://github.com/MyEtherWallet/ethereum-lists/pull/1850]() on 21Sep 20121. 

As my investors are trying to find out the coin BTCA, Bitcoinasia on mew wallet it does not shows up. Although I can see it merged into master [https://github.com/MyEtherWallet/ethereum-lists/blob/master/src/tokens/eth/0x7dB02Aa39A3d0271e4c61C04D03857a10fc922c5.json]()

Please help me to fix it.

**Comment by Modusto509** [comment]
> Hi @gamalielhere thank you for merging  [https://github.com/MyEtherWallet/ethereum-lists/pull/1850]() on 21Sep 20121. 
> 
> As my investors are trying to find out the coin BTCA, Bitcoinasia on mew wallet it does not shows up. Although I can see it merged into master [https://github.com/MyEtherWallet/ethereum-lists/blob/master/src/tokens/eth/0x7dB02Aa39A3d0271e4c61C04D03857a10fc922c5.json]()
> 
> Please help me to fix it.

https://api.blockchair.com/bitcoin/transactions?s=time%28desc%29
