### ISSUE TITLE
COSS has blank value for decimals

### ISSUE THREAD

**Issue by ligi** [MyEtherWallet/ethereum-lists#227]
via https://github.com/MyEtherWallet/ethereum-lists/commit/910d0392d7e81911908cf7a369c29bff910a6bae

**Comment by tayvano** [comment]
Got it. Pushing another round in a moment. I was unaware, but apparently people are using this more than I thought and I'm doing a terrible job at keeping it up to date.

Can you give me a quick run down (or point me to where you did before) of how to run your compile script thingy

**Comment by ligi** [comment]
no worries - you just need to run:

`./gradlew run`

in the root directory of the project.  We could also set this up so it automatically happens for PRs - are you coming to DevCon3? Then we could talk about this in person.

Just for the recent commit - this needs to be merged first:

https://github.com/MyEtherWallet/ethereum-lists/pull/228

as there is this new field ens_address

I am using this repo now in 2 places: issuETH and WALLETH

**Comment by tayvano** [comment]
A few of the exchanges are using it to prevent sending ETH to ICOs and recognize tokens as well. My goodness.

Yes—we will be at devcon. Let's discuss and we'll include @skubakdj as we will likely put a cached version of these up on our API somewhere for the world to use. Want to nail down a process and you have been so helpful with all this.

**Comment by tayvano** [comment]
Is travis the best way to do that?

I'm being lazy ATM, but moving forward (when v4 launches), I'll be removed as admin and everything will go through PRs and we can do protected branches, travis, or whatever.

Seeing as this is being used in production envirornments today, probably best to get that set up sooner rather than later. Lets def discuss during devcon :)

**Comment by ligi** [comment]
you can also do it with travis. But I am using kontinuum (https://github.com/ligi/kontinuum) - so the reports end up on IPFS
