### ISSUE TITLE
new tokens

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/ethereum-lists#252]
- [x] https://confideal.io
https://t.me/confidealioeng
https://www.reddit.com/r/Confideal/
support@confideal.io
+"address":"0x5301c5e92e03474a751d015aeed0873a4db01357",
 +"symbol":"CDL",
 +"decimal":18,

- [x] +"address":"0xfad572db566e5234ac9fc3d570c4edc0050eaa92",
 +"symbol":"BTH",
 +"decimal":18,
Website: https://www.bytether.com/
Slack: https://bytether.slack.com
Reddit: https://www.reddit.com/r/bytether/
Facebook: https://www.facebook.com/Bytether/
Twitter: https://twitter.com/bytether

**Comment by 409H** [comment]
@tayvano Are these on mainnet?

**Comment by tayvano** [comment]
@409H Yes, sorry for not clarifying.
