### ISSUE TITLE
DAI/MKR/Old_MKR Not Showing Up In Default Tokens List

### ISSUE THREAD

**Issue by NiklasKunkel** [MyEtherWallet/ethereum-lists#318]
Our new stablecoin DAI, the new MKR token, and a rename of the Old MKR token were added in PR #286.

I tested these in the UI and got the following:

1. DAI is not listed in the UI
<img width="407" alt="dai_not_listed" src="https://user-images.githubusercontent.com/1817533/34499809-abe1d304-efbc-11e7-8ebc-3b4e6d70c5f4.png">

2. The MKR ticker is listed but still seems to use the OLD_MKR address rather than the new MKR address that was defined in the PR.
<img width="248" alt="new mkr token not recognized" src="https://user-images.githubusercontent.com/1817533/34500994-d9d102c6-efc1-11e7-9919-ea41b1ea4319.png">

3. OLD_MKR is not listed in the UI (still listed as MKR see above^)
<img width="432" alt="old_mkr" src="https://user-images.githubusercontent.com/1817533/34501033-023472fc-efc2-11e7-957e-568634033af5.png">

**Comment by ligi** [comment]
Thanks for the feedback - but the issue should be opened for the MEW UI repo as the problem is there - not this repo which just provides data.
