### ISSUE TITLE
Myetherwallet generated 2 different addresses (lost all my funds)..please help!

### ISSUE THREAD

**Issue by CryptoKnight8** [MyEtherWallet/ethereum-lists#337]
Hi,
Not sure if this is the right place but hopefully somebody can help me out.

Please see below the message I sent to support@myetherwallet.com....urgently looking for some advice as I am quite new to the Crypto world and I think I might have been hacked. 
Dear support team,

I am highly upset as I have lost all my funds that I sent to myetherwallet.com this morning.

I logged on to the site and made sure that it was the right site...https://myetherwallet.com and showed that it was secured. After the site loaded I went to the wallet info link and put in my Private Key. 

I then proceeded to put in my Private Key but for some reason before I entered the last digit the "Unlock" function link came up...thought this was a bit strange but nonetheless continued as I was on the SECURE SITE. I went to my www.luno.com wallet and transferred all my funds to the address that was shown as my wallets address. On my LUNO wallet it showed that the transaction had gone through, when I went back to myetherwallet the funds were not there but I realized that my address had changed from the original one.

This is the address my wallet gave me at the time 0x243e90C79BAcE59843d923E34C78c3A6D5CbC942  trx 0xc4c5d44829ad74a5be56e9d00e02e928e5e3256e4bec005d1ede27e4b4fd4742I copied it and pasted it to make sure it would go through...only to find out when I logged back into myetherwallet that this was not my address???

After more investigation I discovered that my previous transfer from my Luno wallet was also a different address 0x006284478527c99c53F541963Bf945670C44993a trx 0xbdde1098d01a743c41e46d8276b31b5c3beb9e90ab9f3f17effed3d2faca684a...this transaction appeared in myetherwallet although it was the incorrect address....the weirdest thing is I transferred from my etherwallet to bezop.io's ICO and the transaction showed on etherscan.io as successful but no tokens in my Bezop wallet....then after a few hours  checked again and saw that it ran out of gas. Question here is, will this money be sent back to address 0x006284478527c99c53F541963Bf945670C44993 which is not mine in any case.

Please help if you can....as sated above I am not sure if this is the right place to query this, please redirect me then if possible.

Thanks

**Comment by ligi** [comment]
I am sorry for your problem - but this is really the wrong repo/place for your problem

**Comment by 409H** [comment]
As @ligi said, this is the wrong repository. 

Please open your issue over at https://github.com/kvhnuke/etherwallet

**Comment by CryptoKnight8** [comment]
Thank you for the response. Much appreciated
