### ISSUE TITLE
Discussion: json-file per token

### ISSUE THREAD

**Issue by ligi** [MyEtherWallet/ethereum-lists#347]
Was just preparing the PR for WETH (https://github.com/MyEtherWallet/ethereum-lists/pull/346) and had the following thought:

I would suggest moving from the fat json to multiple smaller ones and assemble them just for usage to one file. I see the following advantages:

 * easy to add a new one - just copy an old one or a template and edit it - instead of editing in this huge json which we now have
 * easier reviewing - better visibility of changes
 * we can get sorting for free
 * we get deduplication of symbols for free 

what do you think @tayvano @409H ?
I would write the splitter/joiner and make the PR - but we should make a consolidated effort to try to close all PRs before and merge things timely to not break PRs and invalidate done work in the transition period this way.

**Comment by 409H** [comment]
Are you proposing we have 1 JSON file per token?

**Comment by ligi** [comment]
yes - in the repo - for consumption in apps like MEW or WALLETH they would be combined to one large json containing the array as currently

**Comment by 409H** [comment]
Gotcha. Would they be combined into one large json with something like a CI or is that down the consumers side?

**Comment by ligi** [comment]
Could be done with a CI - would add this to the scripts and kontinuum could build them like it is building the current minified jsons:

https://gateway.ipfs.io/ipfs/QmeUvS1KxRobZD5fjPeAL6jKLuyB7xve1LZ4G5zAmz2eqm

**Comment by 409H** [comment]
Great - then I see no issue in doing it as you propose 👍

**Comment by tayvano** [comment]
I agree. We discussed this as well. We will likely include token symbol, name, decimals, address in one API endpoint (and with build of MEW) and API endpoints for each individual token with the additional data.

**Comment by ligi** [comment]
now implemented in the ethereum-lists organisation: http://walleth.org/2018/02/15/ethereum-lists
