### ISSUE TITLE
Discussion: remove small from repo

### ISSUE THREAD

**Issue by ligi** [MyEtherWallet/ethereum-lists#361]
Elevating this from commit comment to issue to increase visibility:

https://github.com/MyEtherWallet/ethereum-lists/commit/03839ea72f31565aa1cadb9edde0c5d4568c92f7#commitcomment-26702323

just bit me here: https://github.com/MyEtherWallet/ethereum-lists/pull/358#issuecomment-357540246

really think this should be removed - otherwise also fixes have to be made in both - with new ones this can also lead to friction/trouble in the future - let's please remove that

**Comment by tayvano** [comment]
Sorry @ligi — was from my work syncing across the current MEW repo and this one. Not needed and will remove.

**Comment by ligi** [comment]
Great to hear & no need to be sorry!
