### ISSUE TITLE
Future after MyCrypto/MEW split

### ISSUE THREAD

**Issue by ligi** [MyEtherWallet/ethereum-lists#432]
will this project continue here?

**Comment by tayvano** [comment]
I was hoping so as many people are relying upon it and there are links everywhere. However, kvhnuke has revoked my write access so I am no longer about to merge pull requests. Would you like to start a new repo and start it with the new single-file-per-token as discussed?

**Comment by ligi** [comment]
This is really sad to hear and I really hope the wounds between you and kvhunke will heal at some point. Think I will do the repo then ..
Do you have objections to it being a repo in the WallETH organisation? Or would you prefer it to be a separate organisation?

**Comment by 409H** [comment]
I have write access to this repo still if that helps make a decider

**Comment by ligi** [comment]
@409H that's great - but I would love to avoid a bus-factor of 1 ;-)
Thinking about this a bit longer I think I am opening a new organisation for this to keep it neutral and learn from history ..

**Comment by tayvano** [comment]
I'll do whatever makes the most sense for the largest amount of people. The intentions of this repo was always far more global than what it is right now so I'm open to recommendations or others to take to lead and tell me how I can help

**Comment by 409H** [comment]
> Thinking about this a bit longer I think I am opening a new organisation for this to keep it neutral and learn from history ..

When you do, please can you link me?

**Comment by ligi** [comment]
@409H already invited you to the organisation - will be https://github.com/ethereum-lists - didn't you get the invitation? @tayvano already joined as far as I see

**Comment by 409H** [comment]
@ligi thanks! I didn't see the invite come through, but I've just accepted

**Comment by ligi** [comment]
> @ligi thanks! I didn't see the invite come through, but I've just accepted

You are very welcome! The good thing about the whole situation I can now set up a ci-server to automate some work as I had in mind but not the permission (context: https://github.com/MyEtherWallet/ethereum-lists/issues/347 https://github.com/MyEtherWallet/ethereum-lists/pull/37 https://github.com/MyEtherWallet/ethereum-lists/issues/227 https://github.com/MyEtherWallet/ethereum-lists/pull/28)

**Comment by ligi** [comment]
the ethereum-lists org is officially open: http://walleth.org/2018/02/15/ethereum-lists
Also did the split/merging suggested in #347

**Comment by kvhnuke** [comment]
Hey everyone, @SteveMieskoski from MEW team will be maintaining this list. He is also working on a nodejs app to merge all different lists into one. So Im totally cool with you guys using a seperate repo as well since we will merge it here at the end!

**Comment by ligi** [comment]
@kvhnuke great! You can also use the script I have done for merging - it is MIT licensed.

**Comment by kvhnuke** [comment]
@ligi that's awesome, one less thing to do. Can you post the link?

**Comment by ligi** [comment]
@kvhnuke Sure thing: https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/Main.kt

This one assembles 2 json files for each network: one full one with all fields and a minified one with only address, name, symbol and decimals

It is also doing it that way that the CI-Server picks it up and uploads the stuff per commit to IPFS - looks like this then:
https://gateway.ipfs.io/ipfs/QmPQDKrGDGBW3gnyu8iGUsV42bckU22tx4M1415iVhkWCZ

**Comment by ligi** [comment]
@kvhnuke what do you think about adding a "version" field to the token-json. I am thinking about merging strategies - we should really avoid that things diverge. It is easy to merge new tokens - it is a bit more problematic for updates like https://github.com/ethereum-lists/tokens/pull/4

**Comment by soc1c** [comment]
confused! https://github.com/ethereum-lists/urls/issues/1

**Comment by gamalielhere** [comment]
@soc1c what are you confused about?

**Comment by soc1c** [comment]
which repository to use.
