### ISSUE TITLE
Adding your Token as a Default Token

### ISSUE THREAD

**Issue by aj07** [MyEtherWallet/ethereum-lists#472]
LALA token PR has been merged but still it's not showing there as Default token. Will you please take a look into it?

**Comment by aj07** [comment]
@SteveMieskoski When will the next version of MEW will be released so that I can see LALA tokens?
ref https://github.com/kvhnuke/etherwallet/issues/1644

**Comment by gamalielhere** [comment]
@aj07 LALA token should be there now. Closing this.

**Comment by aj07** [comment]
Thanks @gamalielhere
