### ISSUE TITLE
Remove the duplicate DOW from default tokens. 

### ISSUE THREAD

**Issue by vpanwar821** [MyEtherWallet/ethereum-lists#505]
Dow token was already added into the default tokens but due to some reasons we changed the dow token contract address and created a PR to change the address of dow token. The PR was successfully merged and we can see the Dow in the default tokens but the issue is we can see the older dow as well in the default list so there will be two tokens(dow) with the same name. Could you please look into this issue.
PR reference:#477
![dow](https://user-images.githubusercontent.com/32017234/37088139-5bb39280-2222-11e8-87c7-1ef27e06ba34.png)

**Comment by gamalielhere** [comment]
Removed on this repo. And removed on the other list here: [#1673](https://github.com/kvhnuke/etherwallet/pull/1673)
