### ISSUE TITLE
EDU to LEDU update

### ISSUE THREAD

**Issue by ArtemiusUA** [MyEtherWallet/ethereum-lists#540]
Hi.
Some time ago I have submitted change from EDU to LEDU token symbol. PR was merged and I see correct token symbol in tokens-eth.json, but not on MEW site.
Can you please take a look.
Thanks!

**Comment by gamalielhere** [comment]
@ArtemiusUA I apologize for the delay, it will be in the next upcoming release. Please refer to [#1703](https://github.com/kvhnuke/etherwallet/pull/1703)
