### ISSUE TITLE
Json parse error PHP 5

### ISSUE THREAD

**Issue by Adioboy** [MyEtherWallet/ethereum-lists#768]
JSON data not parsing in PHP 5.6.33, may be the use or non-use of commas after dates. Some have it, some don't. Works when close object without comma :)

**Comment by gamalielhere** [comment]
@Adioboy What file are you specifically referring to?

**Comment by Adioboy** [comment]
@gamalielhere apologies, its the addresses/addresses-darklist.json file

**Comment by gamalielhere** [comment]
@Adioboy Seems like none of them have commas at the end. Are you certain you have the current version?

**Comment by Adioboy** [comment]
@gamalielhere thank you for the change :) I'll close the thread
