### ISSUE TITLE
dumping shit here so I can focus on other things

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/ethereum-lists#8]
from https://bitcointalk.org/index.php?topic=1689585.20

bitcoin-wallet.net
ethereum-wallet.net
www.ethereum-wallet.info
https://twitter.com/EthereumWallets
www.ether-wallet.net

0xc568ca90c5d887ad418b2007c7cf0b0eb86c9044
0x9b4167863B0ba8D91f7751517345a7d93880D6dC
0xEf9e06eE6C6aDdE29237E55A20E6743c92575eBe

**Comment by tayvano** [comment]
myetherwaallet[.]com
myethetrwallet[.]com
myetherwaliiet[.]com 
myetherwalle3t[.]com 
myetherwallet[.]com[.]gl 
myetherwallet[.]com[.]ht 
myetherwallet[.]com[.]ua 
myetherwallet[.]top 
myetherwallewt[.]com 
myethsrwallet[.]com

**Comment by tayvano** [comment]
coindash[.]ml
coindash[.]ru
blocklichan[.]info
bloclkicihan[.]info

**Comment by ChaceHunter** [comment]
Added all the sites to urls-darklist.json in PR #10 
Have not added addresses due to not knowing enough details to comment, nor whether they are light or dark. 😸
