### ISSUE TITLE
Suggestion: Search on contracts/tokens list

### ISSUE THREAD

**Issue by IRMkz** [MyEtherWallet/ethereum-lists#852]
Hello

as list of Contracts is going bigger, is possible to add search field on 1. place when that dropdown list is open? Meaning 1. line will be search bar, 2. line will be first contract etc.

It will help find contract faster, also on mobile devices this dropdown menu is not working with smooth scrolling, so scrolling over it is very slow.
Similar can be done on tokens list.

thanks for considering.

**Comment by bevaliando** [comment]
contractsDirectory

**Comment by m1ck2** [comment]
Drain boobs bounce dog
