### ISSUE TITLE
Wrong decimals for two ERC20 tokens

### ISSUE THREAD

**Issue by s0lness** [MyEtherWallet/ethereum-lists#920]
Hi,

I was checking the ERC20 list on MEW (https://github.com/MyEtherWallet/ethereum-lists/tree/master/src/tokens/eth) and noticed two tokens had wrong decimals:

- Cardstack token (0x954b890704693af242613edef1b603825afcd708) written as 0 decimals in the json but actually has 18
- Edu token (0x2a22e5cca00a3d63308fa39f29202eb1b39eef52) -> written as 6 decimals but actually has 18

**Comment by gamalielhere** [comment]
New push should fix these.
