### ISSUE TITLE
Adding GUSD 

### ISSUE THREAD

**Issue by FabriceDautriat** [MyEtherWallet/ethereum-lists#939]
Could you please add the following token ?

https://etherscan.io/token/0x056fd409e1d7a124bd7017459dfea2f387b6d5cd

https://gemini.com/dollar/

ticker : GUSD
SC address : 0x056fd409e1d7a124bd7017459dfea2f387b6d5cd
Decimals : 2

Thanks a lot for your help and support.

**Comment by gamalielhere** [comment]
It should be added to this repo and the token added to myetherwallet.com in a new release this week.
