### ISSUE TITLE
Create a unique id per token entry

### ISSUE THREAD

**Issue by aldoborrero** [MyEtherWallet/ethereum-lists#949]
Hi @gamalielhere, I'm Aldo from EthVM :),

Currently, we are using these awesome lists on EthVM to gather known and verified tokens on the explorer. Alongside with this project, we are using CoinGecko API as well to cross-match with latest exchange rates.

So far so good (as you can see in below image):

<img width="535" alt="screen shot 2019-02-08 at 13 45 17" src="https://user-images.githubusercontent.com/82811/52479119-d97ea800-2ba7-11e9-8d97-1bb1d956d69a.png">

The only remaining "bit" is that for some tokens they may have the same "symbol" (i.e: HOT that can be HoloToken or HydroToken).

CoinGecko API in order to differentiate them, uses the concept of unique id like below:

<img width="212" alt="screen shot 2019-02-08 at 13 50 28" src="https://user-images.githubusercontent.com/82811/52479331-8eb16000-2ba8-11e9-96aa-ffc65fa25f9d.png">

<img width="223" alt="screen shot 2019-02-08 at 13 50 43" src="https://user-images.githubusercontent.com/82811/52479338-9113ba00-2ba8-11e9-833b-29998364a190.png">

I've been scouting their API and doesn't allow you to gather a exchange rate AND general eth token information (so, in reality, there's no way of cross-matching their data with this tokens list).

Maybe, as a proposed solution, we can add those id fields to our tokens list in order to have a unique token identifier despite the token symbol is the same or not.

What do you think?

**Comment by ligi** [comment]
isn't the address a unique id enough?

**Comment by aldoborrero** [comment]
@ligi initally that is I was thinking when I was coding it, but the response for the call doesn't include it unluckily (unless you query each token one by one to obtain and check it). 

E.g when querying (API documentation here: [](https://www.coingecko.com/api/docs/v3#/):

`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false`

```
{
    "id": "basic-attention-token",
    "symbol": "bat",
    "name": "Basic Attention Token",
    "image": "https://assets.coingecko.com/coins/images/677/large/basic-attention-token.png?1547034427",
    "current_price": 0.114188018032104,
    "market_cap": 140502542.767705,
    "market_cap_rank": 38,
    "total_volume": 17722755.8873965,
    "high_24h": 0.122696742385362,
    "low_24h": 0.111469665352964,
    "price_change_24h": -0.00321968162650817,
    "price_change_percentage_24h": -2.74230875476658,
    "market_cap_change_24h": -3253061.91692704,
    "market_cap_change_percentage_24h": -2.26291136548278,
    "circulating_supply": "1230449089.047178443452212287",
    "total_supply": 1500000000,
    "ath": 0.959505426969072,
    "ath_change_percentage": -88.1257243314599,
    "ath_date": "2018-01-09T00:00:00.000Z",
    "roi": {
      "times": 5.68753378508096,
      "currency": "eth",
      "percentage": 568.753378508096
    },
    "last_updated": "2019-02-08T14:07:47.862Z"
  },
```

According to my checks there are 266 tokens/coins that shares the same symbol over 3900 (again, CoingGecko mixes Crypto coins and Eth tokens and I didn't saw an option to filter those). 

So, my other possible idea is to query each of those 266 and filter them by obtaining the detail on CoinGecko and cross-matching it with the address (but I was trying to avoid that).

**Comment by kvhnuke** [comment]
will this be any help https://www.coingecko.com/api/docs/v3#/coins/get_coins__id__contract__contract_address_
I also reached out to Bobby from CoinGecko may be there is a different way

**Comment by tmlee** [comment]
@aldoborrero, as @kvhnuke mentioned, would that direct call using contract address resolve the problem?

It does sound like you are looking to map the `contract address` from EthVM and a coin list that returns contract address in an API like https://api.coingecko.com/api/v3/coins/list would be helpful?
