### ISSUE TITLE
Bankcoin Cash (BKC) Please add Default List

### ISSUE THREAD

**Issue by bankcoincash** [MyEtherWallet/ethereum-lists#982]
Token : Bankcoin Cash
Symbol : BKC
Contract :0xc88Be04c809856B75E3DfE19eB4dCf0a3B15317a 
Logo Link : https://bankcoin-cash.com/bankcoincash.png
Please add Default List

**Comment by Jessey20** [comment]
https://bankcoin-cash.com/bankcoincash.png
